---
- name: Call multiple childplaybooks for apache2
  hosts: all
  tasks:
    - name: Call multiple child playbooks
      include: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
...          
