---
- name: Capture od info of managed nodes
  hosts: all
  tasks:
    - name: Capture os name
      debug: msg="{{ansible_distribution}}"
    - name: Capture the os version
      debug: msg="{{ansible_distribution_version}}"
    - name: Capute os major version
      debug: msg="{{ansible_distribution_major_version}}"    
