---
- name: fetch the file from server1
  hosts: 172.31.42.71
  tasks:
    - name: Fetch file
      fetch:
        src: file1
        dest: /tmp
- name: Copy file to server2
  hosts: 172.31.41.162
  tasks:
    - name: copy file
      copy:
        src: /tmp/172.31.42.71/file1
        dest: /tmp
...


