---
- name: Create file based on a condition
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: Create file
      file:
        name: /tmp/file1
        state: touch
      when: a==10
...        

