---
- name: Check if folder f1 is present if nat create a file f1
  hosts: all
  tasks:
    - name: Check for folder f1
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Create file f1 if folder f1 is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false     
...          
