---
- name: Configure apache2 on ubuntu and httpd on ReaHat
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu
      apt: 
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Insatll httpd on RedHat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "welcome to IntelliQIT"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubuntu
      service: 
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RedHat
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache2/httpd response on all managed nodes
      uri: 
        url: "{{item}}"
        status_code: 200
      with_items: 
        - http://172.31.42.71
        - http://172.31.41.162
        - http://172.31.37.89    
